zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000/resource
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
logging:
  level:
    org.springframework.cloud: DEBUG
security:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
      accessTokenUri: http://localhost:9999/uaa/oauth/token
    resource:
      userInfoUri: http://localhost:9999/uaa/user